from app.services.hearing_package_engine import build_hearing_package


def _html_list(items):
    if not items:
        return "<p>None.</p>"
    return "<ul>" + "".join([f"<li>{item}</li>" for item in items]) + "</ul>"


def build_binder_html(db, investigation_id):
    pkg = build_hearing_package(db, investigation_id)

    # map claim_id → exhibit number
    exhibit_map = {e["claim_id"]: e["exhibit_number"] for e in pkg.get("exhibit_index", [])}

    # issues with inline exhibit refs
    issue_items = []
    for i in pkg.get("issues", []):
        refs = []
        for ev in i.get("evidence", [])[:3]:
            ex = exhibit_map.get(ev.get("claim_id"))
            if ex:
                refs.append(ex)
        ref_text = f" (See Exhibits {', '.join(refs)})" if refs else ""
        issue_items.append(f"Issue {i['issue']}: {i['analysis']} Conclusion: {i['conclusion']}{ref_text}")

    exhibit_items = [
        f"{e['exhibit_number']}: claim {e['claim_id']} — {e['excerpt'] or ''} ({e['locator'] or 'no locator'})"
        for e in pkg.get("exhibit_index", [])
    ]

    html = f'''<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Hearing Package</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.5; }}
h1 {{ font-size: 22px; }}
h2 {{ font-size: 18px; margin-top: 24px; }}
ul {{ margin-top: 0.4rem; }}
.footer {{ position: fixed; bottom: 10px; font-size: 10px; width: 100%; text-align: center; }}
</style>
</head>
<body>
<h1>Hearing Package</h1>

<h2>Adjudicator Summary</h2>
<p>{pkg.get('adjudicator_summary', '')}</p>

<h2>Issues for Determination</h2>
{_html_list(issue_items)}

<h2>Exhibit Index</h2>
{_html_list(exhibit_items)}

<div class="footer">Generated by OSINT Investigative Workbench</div>
</body>
</html>'''

    return {
        "html": html,
        "suggested_filename": f"hearing_package_{investigation_id}.html",
    }
